# Libitina Definition File (im.Composite)
## Taken from True Reality's Definition File (edited for public use)
## Licensed under the L General License. See L General License.pdf for more information.
## Copyright 2020-2022 GanstaKingofSA (Azariel Del Carmen). ALl rights reserved.

## Pose 1
image libitina 1a = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/a.png")
image libitina 1b = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/b.png")
image libitina 1c = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/c.png")
image libitina 1d = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/d.png")
image libitina 1e = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/e.png")
image libitina 1f = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/f.png")
image libitina 1g = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/g.png")
image libitina 1h = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/h.png")
image libitina 1i = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/i.png")
image libitina 1j = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/j.png")
image libitina 1k = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/k.png")
image libitina 1l = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/l.png")
image libitina 1m = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/m.png")
image libitina 1n = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/n.png")
image libitina 1o = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/o.png")
image libitina 1p = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/p.png")
image libitina 1q = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/q.png")
image libitina 1r = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/r.png")
image libitina 1s = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/s.png")
image libitina 1t = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/t.png")
image libitina 1u = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/u.png")
image libitina 1v = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/v.png")
image libitina 1w = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/w.png")
image libitina 1x = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/1.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 1/x.png")

## Pose 2
image libitina 2a = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/a.png")
image libitina 2b = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/b.png")
image libitina 2c = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/c.png")
image libitina 2d = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/d.png")
image libitina 2e = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/e.png")
image libitina 2f = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/f.png")
image libitina 2g = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/g.png")
image libitina 2h = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/h.png")
image libitina 2i = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/i.png")
image libitina 2j = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/j.png")
image libitina 2k = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/k.png")
image libitina 2l = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/l.png")
image libitina 2m = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/m.png")
image libitina 2n = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/n.png")
image libitina 2o = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/o.png")
image libitina 2p = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/p.png")
image libitina 2q = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/q.png")
image libitina 2r = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/r.png")
image libitina 2s = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/s.png")
image libitina 2t = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/t.png")
image libitina 2u = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/u.png")
image libitina 2v = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/v.png")
image libitina 2w = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/w.png")
image libitina 2x = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 2/x.png")

## Yandere Look for Pose 2
image libitina 2yb = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/2.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/b.png")

## Pose 3
image libitina 3a = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/a2.png")
image libitina 3a2 = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/a.png")
image libitina 3b = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/b.png")
image libitina 3b2 = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/b2.png")
image libitina 3c = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/c.png")
image libitina 3c2 = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/c2.png")
image libitina 3d = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/d.png")
image libitina 3e = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/floating rl eyes.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/e.png")
image libitina 3f = im.Composite((960, 960), (0, 0), "mod_assets/gov.sdc.libitina/Poses/3.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/floating rl eyes.png", (0, 0), "mod_assets/gov.sdc.libitina/Expressions/Pose 3/f.png")
